# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 35a894b7e3c9feb0de69b928af99f4c7efc105559f17943581897b844d582a3fe091dfbb9c136baf0dc4e8107e4358966ef8daf78ce80ad7a6d907020e9088ae

test:
  secret_key_base: 12704f44d369bd90ceff91e51ba7038f328affcd1da473893ae318220b5011fad6c5f93b4aa42f72bf77172a35b33f95a61eaa9ccc5a7b17cc78df10e5796bed

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
